apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-gateway
  template:
    metadata:
      labels:
        app: agri-gateway
    spec:
      containers:
      - name: agri-gateway
        image: sesha1306/agri-gateway:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: agri-gateway
spec:
  type: ClusterIP
  selector:
    app: agri-gateway
  ports:
  - port: 80
    targetPort: 80
