apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-backend
  template:
    metadata:
      labels:
        app: agri-backend
    spec:
      containers:
        - name: backend
          image: sesha1306/agri-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: groq-secret
                  key: api-key
          volumeMounts:                       # ✅ REQUIRED
            - name: model-store
              mountPath: /models
      volumes:
        - name: model-store
          persistentVolumeClaim:
            claimName: model-store-pvc       # ✅ FIXED INDENTATION

---
apiVersion: v1
kind: Service
metadata:
  name: agri-backend
spec:
  selector:
    app: agri-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
