apiVersion: batch/v1
kind: CronJob
metadata:
  name: afta-retrain
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5

  jobTemplate:
    spec:
      backoffLimit: 0   # fail fast, no retries
      template:
        spec:
          serviceAccountName: retrain-sa
          restartPolicy: Never

          containers:
            - name: retrain
              image: sesha1306/agri-backend:latest
              command:
                - python
                - /app/retrain/retrain.py

              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
                - name: DATASET_PATH
                  value: /app/dataset/irrigation_dataset.csv
                - name: MODEL_OUTPUT_PATH
                  value: /app/retrain/final_model.pkl

              volumeMounts:
                - name: agri-data
                  mountPath: /app/dataset
                - name: retrain-state
                  mountPath: /app/retrain_state

          volumes:
            - name: agri-data
              hostPath:
                path: /dataset
                type: DirectoryOrCreate
            - name: retrain-state
              hostPath:
                path: /retrain_state
                type: DirectoryOrCreate

