apiVersion: v1
kind: ServiceAccount
metadata:
  name: retrain-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: retrain-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: retrain-rolebinding
subjects:
  - kind: ServiceAccount
    name: retrain-sa
roleRef:
  kind: Role
  name: retrain-role
  apiGroup: rbac.authorization.k8s.io
