apiVersion: batch/v1
kind: CronJob
metadata:
  name: afta-retrain
spec:
  schedule: "0 3 * * *"   # runs every day at 3 AM
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: retrain
              image: sesha1306/agri-backend:latest
              command: ["python", "retrain/retrain.py"]
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
          restartPolicy: OnFailure