apiVersion: v1
kind: ServiceAccount
metadata:
  name: retrain-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: retrain-role
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: retrain-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: retrain-sa
    namespace: default
roleRef:
  kind: Role
  name: retrain-role
  apiGroup: rbac.authorization.k8s.io
